# Generated by Django 2.1.5 on 2019-02-11 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('struktur_ATA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struktur_ATA.MataPelajaran'),
        ),
        migrations.AlterField(
            model_name='livecode',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struktur_ATA.MataPelajaran'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='mata_pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='struktur_ATA.MataPelajaran'),
        ),
    ]
